# PaperPlane Default Config

title = "PaperPlane"

[base]
folder = "PaperPlane"
static = "./build/frontend/"
debug = false

[blockchain]
type = "ethereum"

[database]
type = "firebase"

[mailer]
host = "smtp.gmail.com"
secure = true
port = 465
user = "contact@mermer.cc"
password = ""

[api]
url = "drophere.io"
pathname = [
  "get | /,/version | Static.Utils.readPackageInfo",
  "post | /upload | Bot.LFS.initialUpload",
  "get | /upload/:jid | Bot.LFS.getMetadata",
  "post | /upload/:jid/:hash | Bot.LFS.uploadSlice",
  "get | /upload/:jid/:hash | Bot.LFS.getSlice",
  "get | /file/:rootHash | Bot.LFS.getMetadata",
  "get | /file/:rootHash/:hash | Bot.LFS.getSlice"
]