# PaperPlane Default Config

title = "PaperPlane"

[base]
folder = "PaperPlane"
static = "./build/frontend/"
debug = false

[blockchain]
type = "ethereum"

[database]
type = "firebase"

[jwt]
secret = "zeAdSm9ZFI8HvlEyWeGJSDLa7mr1GMD5"

[verification]
emailTimeout = 3600000
mobileTimeout = 300000

[mailer]
host = "smtp.gmail.com"
secure = true
port = 465
user = "contact@mermer.cc"
password = ""

[api]
url = "localhost"
pathname = [
  "get | /,/version | Static.Utils.readPackageInfo",
  "post | /letter | Bot.LFS.initialLetter",
  "get | /letter/:lid | Bot.LFS.getLetter",
  "post | /letter/:lid/send | Bot.LFS.sendLetter",
  "post | /letter/:lid/upload | Bot.LFS.initialUpload",
  "delete | /letter/:lid/upload/:fid | Bot.LFS.deleteUpload",
  "get | /letter/:lid/upload/:fid | Bot.LFS.getMetadata",
  "post | /letter/:lid/upload/:fid/:hash | Bot.LFS.uploadSlice",
  "get | /letter/:lid/upload/:fid/:hash | Bot.LFS.getSlice",
  "get | /file/:rootHash | Bot.LFS.getMetadata",
  "get | /file/:rootHash/:hash | Bot.LFS.getSlice",
  "post | /member/ | Bot.Member.register",
  "get | /member/ | Bot.Member.searchUser",
  "get | /member/:account/salt | Bot.Member.checkAccount",
  "get | /member/:account/allowRegister | Bot.Member.allowRegister",
  "get | /resend/email | Bot.Member.resendEmailVerification",
  "get | /verify/email | Bot.Member.emailConfirm"
]