# PaperPlane Default Config

title = "PaperPlane"

[base]
folder = "PaperPlane"
static = "./build/frontend/"
debug = false

[blockchain]
type = "ethereum"

[database]
type = "firebase"

[mailer]
host = "smtp.gmail.com"
secure = true
port = 465
user = "contact@drophere.io"
password = ""

[api]
pathname = [
  "get | /,/version | Static.Utils.readPackageInfo",
  "get | /meta/:hash | Bot.LFS.getMetadata",
  "get | /file | Bot.LFS.initialUpload",
  "post | /file | Bot.LFS.initialUpload",
  "get | /file/:fid | Bot.LFS.getUploadJob",
  "post | /file/:fid/:hash | Bot.LFS.uploadSlice",
  "post | /test/upload | Bot.LFS.testUpload"
]